// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/johan/github/qmk_firmware/keyboards/splitkb/kyria/keymaps/jsve/gslogo.bmp --output /Users/johan/github/qmk_firmware/keyboards/splitkb/kyria/keymaps/jsve --format mono2 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_gslogo_length;
extern const uint8_t  gfx_gslogo[551];
